"""Fixed internal limits for the STT component."""

from __future__ import annotations

MAX_ACTIVE_TRANSCRIPTIONS = 5
MAX_UPLOAD_BYTES = 64 * 1024 * 1024
UPLOAD_PROGRESS_TIMEOUT_SECONDS = 15
TOTAL_UPLOAD_TIMEOUT_SECONDS = 300
TOTAL_TRANSCRIPTION_TIMEOUT_SECONDS = 180
WORKER_KILL_AFTER_SECONDS = 5.0
MAX_WORKER_ERROR_BYTES = 16 * 1024
MAX_WORKER_OUTPUT_BYTES = 4 * 1024 * 1024
MAX_LANGUAGE_CHARS = 32
STARTUP_TIMEOUT_SECONDS = 30.0
